# build environment requires grpc
FROM python
ADD src/client /src
ADD src/project1.proto /src
WORKDIR /src
RUN pip install -r requirements.txt
RUN python3 -m grpc_tools.protoc -I/src --python_out=. --pyi_out=. --grpc_python_out=. /src/project1.proto
ENTRYPOINT /src/sleeper.sh