# build environment requires grpc
FROM kcpu/grpc-cxx AS build
ADD src /src
RUN cd /src && mkdir build && cd build && cmake .. && make

# make smaller image for final deployment
FROM debian:latest AS final

RUN DEBIAN_FRONTEND=noninteractive apt update && apt -y install file

# Copy the executable from the "build" stage.
COPY --from=build /src/build/client /bin/
ADD src/sleeper.sh /

RUN mkdir /work; cd /work; cp /bin/client .

ENV SERVER_HOST="server:50051"
WORKDIR /work
ENTRYPOINT /sleeper.sh